DROP TABLE IF EXISTS `guild_storage_log`;
DROP TABLE IF EXISTS `guild_storage`;
DROP TABLE IF EXISTS `guild_skill`;
DROP TABLE IF EXISTS `guild_position`;
DROP TABLE IF EXISTS `guild_member`;
DROP TABLE IF EXISTS `guild_expulsion`;
DROP TABLE IF EXISTS `guild_castle`;
DROP TABLE IF EXISTS `guild_alliance`;
DROP TABLE IF EXISTS `guild`;